### PR TITLE
added dark mode wrt issue #11

### LINKED ISSUE #11: Add Dark Mode theme
**Describe the feature you'd like**

1. Add dark mode theme. By default the app should work in the theme set on the system. Also, there should be an option given to the user to switch between Dark mode and Light mode themes.
2. Details on color schemes, etc  should be discussed before working on this feature

### PR DESCRIPTION
**Pull request by PratyushSingh07**
# Description

I have added the option to switch between light and dark mode from inside of the app

Fixes #11

## APK Link

[Click here for the APK](https://drive.google.com/file/d/13CIGsnz2lkGfQ5tsq71AMu3_aDvZJF2Z/view)

### CODE REVIEW

**Comment by coder2699** [comment]
Looks good to me. Just small fixes:

1) Use lighter shade for cards, cards are not clearly visible
imgggg (1)

2) Fix color of snackbar, check for all screens.
imgggg (2)

**Comment by PratyushSingh07** [comment]
> Looks good to me. Just small fixes:
> 
> 1. Use lighter shade for cards, cards are not clearly visible
>    imgggg (1)
> 2. Fix color of snackbar, check for all screens.
>    imgggg (2)

@coder2699 the encircled gray space doesn't apperar in the xml file 

Screenshot (494)

**Comment by PratyushSingh07** [comment]
@coder2699 these are the changes , I have updated the PR with the below changes

WhatsApp Image 2022-10-09 at 16 06 26
WhatsApp Image 2022-10-09 at 16 06 26 (1)

**Comment by coder2699** [comment]
@PratyushSingh07 have you shared updated APK link?

**Comment by PratyushSingh07** [comment]
> @PratyushSingh07 have you shared updated APK link?

https://drive.google.com/file/d/13CIGsnz2lkGfQ5tsq71AMu3_aDvZJF2Z/view?usp=sharing

here is the updated link

**Comment by coder2699** [comment]
give @PratyushSingh07 75 points

**Pull request merged**
